[project]
name = "ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=0.3.8",
    "langchain-openai>=0.3.0",
    "mcp-use>=1.3.11",
    "python-dotenv>=1.0.0",
]
